name: Preview build

on:
  workflow_dispatch:
  
  # push:
  #   branches: 
  #     - "**"

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      PARENT_REPOSITORY: 'turbotio/steampipe.io'
      CHECKOUT_BRANCH: 'staging'
      PR_AGAINST_BRANCH: 'staging'
      OWNER: 'turbotio'
      GITHUB_TOKEN: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
    steps:
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v2
      #   with:
      #     token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
      #     repository: turbotio/steampipe.io
      #     event-type: vercel-flow
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      - name: Set Git config
        run: |
          mkdir -p ~/.config/turbot
          echo "templateDefinitions: /home/runner/work/turbot-mods/turbot-mods/new-templates" > ~/.config/turbot/template.yml
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Checkout main branch
        uses: actions/checkout@v2
        with: 
        # #   repository: steampipe-docs
          repository: turbotio/steampipe.io
          token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          ref: main
      - name: run action
        id: run_action
        uses: releasehub-com/github-action-create-pr-parent-submodule@v1
        with:
          github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          parent_repository: ${{ env.PARENT_REPOSITORY }}
          checkout_branch: ${{ env.CHECKOUT_BRANCH}}
          pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
          owner: ${{ env.OWNER }}        
      # - name: Create new branch
      #   uses: peterjgrainger/action-create-branch@v2.2.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
      #   with:
      #     branch: 'workflow-branch-2'          
      # - name: Checkout working branch
      #   uses: actions/checkout@v2
      #   with: 
      #   #   repository: steampipe-docs
      #     repository: turbotio/steampipe.io
      #     token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
      #     ref: workflow-branch-2
      # - name: Add submodules
      #   run: |
      #     git submodule add https://github.com/turbot/steampipe-docs.git
       

      # - uses: convictional/trigger-workflow-and-wait@v1.6.1
      #   with:
      #     owner: abhiturbot
      #     repo: turbotio/steampipe.io
      #     github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
      #     ref: main
      #     workflow_file_name: build-production.yml


      # - name: Create branch
      #   if: $GITHUB_BRANCH_EXIST == ""
      #   run: |
      #     echo "Branch Exist"
      #     echo $GITHUB_BRANCH_EXIST
      #     echo $gihub.ref_name
      #   else:
      #   run: |
      #     echo "Branch doesnot exist"

