name: Preview build

on:
  workflow_dispatch:
  
  # push:
  #   branches: 
  #     - "**"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
        # with: 
        #   repository: steampipe-docs
          # repository: turbotio/steampipe.io
          # token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: abhiturbot
          repo: turbotio/steampipe.io
          github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
          ref: main
          workflow_file_name: build-production.yml


      # - name: Create branch
      #   if: $GITHUB_BRANCH_EXIST == ""
      #   run: |
      #     echo "Branch Exist"
      #     echo $GITHUB_BRANCH_EXIST
      #     echo $gihub.ref_name
      #   else:
      #   run: |
      #     echo "Branch doesnot exist"

