name: Preview build

on:
  workflow_dispatch:
  
  # push:
  #   branches: 
  #     - "**"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout working branch
        uses: actions/checkout@v2
        # with: 
        #   repository: steampipe-docs
          # repository: turbotio/steampipe.io
          # token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      - name: Check branch exists
        run: |
          echo "Branch name"
          a=`git rev-parse --verify --quiet main`
          echo $a

      # - name: Create branch
      #   if: $GITHUB_BRANCH_EXIST == ""
      #   run: |
      #     echo "Branch Exist"
      #     echo $GITHUB_BRANCH_EXIST
      #     echo $gihub.ref_name
      #   else:
      #   run: |
      #     echo "Branch doesnot exist"

